### Logout and Invalidate Token
DELETE http://localhost:3001/api/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyQGV4YW1wbGUuY29tIiwiaWQiOjMsImlhdCI6MTc0MDg0ODEzNCwiZXhwIjoxNzQwODUxNzM0fQ.5WuNrpQGKbnuSlsdRfCi1SSnkfTEwz9wpfQUxCHAzWA