version: '3.8'

services:
  todo-frontend:
    image: todo-frontend  # Name of the frontend production image
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile  # Use production Dockerfile
    environment:
      - VITE_BACKEND_URL=http://nginx/api  # Use Nginx as the backend URL
    container_name: todo-frontend
    depends_on:
      - todo-backend
    restart: always

  todo-backend:
    image: todo-backend  # Name of the backend production image
    build:
      context: ./todo-backend
      dockerfile: Dockerfile  # Use production Dockerfile
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
    container_name: todo-backend
    depends_on:
      - mongo
      - redis
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data
    restart: always

  nginx:
    image: nginx:1.20.1
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Use production Nginx config
    ports:
      - 80:80  # Expose Nginx on port 80
    depends_on:
      - todo-frontend
      - todo-backend
    restart: always

volumes:
  mongo_data:
  redis_data: