###
POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "MongoDB is webscale",
    "important": false,
    "userId": 1
}

###
POST http://localhost:3001/api/notes
content-type: application/json

{
    "content": "Relational databases rule the world",
    "important": true, 
    "userId": 1
}

###
POST http://localhost:3001/api/notes
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRyYWplbmQ5IiwiaWQiOjEsImlhdCI6MTc0MDc3MDc4Nn0.UvJcFORj_nXiLL8kQwOL3AglkxOz2TXGX2lK2-LDhck

{
    "content": "MongoDB is webscale",
    "important": false
}

###
POST http://localhost:3001/api/notes
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRyYWplbmQ5IiwiaWQiOjEsImlhdCI6MTc0MDc3MDc4Nn0.UvJcFORj_nXiLL8kQwOL3AglkxOz2TXGX2lK2-LDhck

{
    "content": "Relational databases rule the world",
    "important": true
}

###
POST http://localhost:3001/api/notes
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJzaG04NyIsImlkIjoyLCJpYXQiOjE3NDA3NzA5MjZ9.Na-PaXHlMHM_rCohB0rfI9S4ND7JE0Rc4qvyrjSKvjY

{
    "content": "Note 1 content",
    "important": false
}

###
POST http://localhost:3001/api/notes
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJzaG04NyIsImlkIjoyLCJpYXQiOjE3NDA3NzA5MjZ9.Na-PaXHlMHM_rCohB0rfI9S4ND7JE0Rc4qvyrjSKvjY

{
    "content": "Note 2 content",
    "important": true
}